### ISSUE TITLE
foundry v11 not supported

### ISSUE THREAD

**Issue by PwQt** [League-of-Foundry-Developers/fvtt-module-popout#102]
As of now Foundry v11 is not supported. It might be only the issue of updating the manifest. 

![obraz](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/assets/12457218/2bf42c10-0fe8-4fd2-adf4-7a0249d1d0c6)

**Comment by Ancyker** [comment]
Yeah, I manually modified `module.json` to change max core to 11 and it seems to work fine.

**Comment by audstanley** [comment]
Works great in v11.3 - added a pull request [#103](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/pull/103)

**Comment by Posnet** [comment]
Currently climbing Kilimanjaro, will review and merge when I get back on the 18th of June.

**Comment by Rooksgate** [comment]
> Currently climbing Kilimanjaro, will review and merge when I get back on the 18th of June.

Seriously? If so, that is awesome.

**Comment by Posnet** [comment]
Fixed in v2.14

**Comment by Posnet** [comment]
> > Currently climbing Kilimanjaro, will review and merge when I get back on the 18th of June.
> 
> Seriously? If so, that is awesome.

;)

![](https://lh3.googleusercontent.com/pw/AJFCJaX0LwHIUcfaTjcAN0-RIGS1DAn5fCStH8c_7HeiJBcDG4pUoZ-qY_TOEUUQJEWwy8i6xMZFXwVW5hDRCqEeNU1wE0s-CebY4tatEn-rhOEQyCN7mUR83H4X2XEthNHlwUM3bEJ4IVLEeghwawo_1K0akQ=w2150-h1612-s-no?authuser=0)
