### ISSUE TITLE
Support for v11

### ISSUE THREAD

**Issue by amazingrando** [League-of-Foundry-Developers/fvtt-module-popout#106]
Is updating this module for Foundry v11 on the roadmap? Thanks!

**Comment by Posnet** [comment]
It already does. Is there functionality not working in v11?

**Comment by amazingrando** [comment]
I double-checked my setup and it turns out that I'm the problem here. When
upgrading from v10 to v11 of Foundry you have to uninstall Foundry first
and I did not do that.
