### ISSUE TITLE
Enableing Popout removes close window options

### ISSUE THREAD

**Issue by Macdonaldfr** [League-of-Foundry-Developers/fvtt-module-popout#116]
I installed Popout! on my Forbidden Lands server and when I enable it the pop out portion works like a dream.  However I can find no options or combination thereof that result in the close button continuing to exist meaning I need to either close everything open with esc or pop the window out then close the new window.
![image](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/assets/78168435/c5041cbd-8e2d-469c-843b-1e86734c836d)

**Comment by Macdonaldfr** [comment]
I have alot of stuff (like 45 mods or so), Turns out I was able to find a
work around by changing the Forbidden Lands Setting "Collapse Sheet Header
Buttons" to enabled.

**Comment by Posnet** [comment]
Okay. Popout also has the option to make its button just an icon to save space as well.
