### ISSUE TITLE
DnD5e Default sheet popout 2.16 displays badly for DnD 5e 3.1.2 on v 11.315 stable

### ISSUE THREAD

**Issue by zabu61** [League-of-Foundry-Developers/fvtt-module-popout#123]
Per the title, I am using DnD5e 3.1.2 on foundry 11.315 on Forge with PopOut 2.16

Just upgraded a host of modules for all sorts of compatibility, but popout of the new Default 5e Character sheet is basically a fail. 

Pictures are attached for more clarity.

![PoppedCharacterSheetFail](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/assets/30198757/1c0a41a9-6fd3-4471-9518-6e1499d49759)
![unpopped5eCharacterSheet](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/assets/30198757/6af95114-7c93-4cdd-ae95-d59216cc1899)

**Comment by Posnet** [comment]
Due to multiple bugs in firefox, PopOut! cannot support it.
See the README or https://github.com/foundryvtt/dnd5e/pull/3048#issuecomment-1973339869 for details
