### ISSUE TITLE
Bug - the file explorer window changes positions when used, making regular usage impossible.

### ISSUE THREAD

**Issue by Bearsomez** [League-of-Foundry-Developers/fvtt-module-popout#31]
When popping out, say, a character sheet, and attempting to set its token to a certain file, the file explorer window will pop up. 
![image](https://user-images.githubusercontent.com/5511848/97181589-be006a00-179b-11eb-802a-30b04dce9227.png)
If a user changes the folder or goes up a folder though, that window will change its position - clipping through the viewport and making regular usage impossible.
![image](https://user-images.githubusercontent.com/5511848/97181613-c48ee180-179b-11eb-9a92-5418a0fefef8.png)
Hopefully I'm explaining this issue well enough.

**Comment by epicmusic42** [comment]
Both myself and my players have been having this issue with other windows as well. It seems that anything that opens a new window gets stuck so it's unusable if you open it in a window that's been popped out. (If I need to fill a new bug report, I can. I figured probably easier to comment on this one though).

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue as soon.
