### ISSUE TITLE
Can't utilitize ESC when sheet popped out

### ISSUE THREAD

**Issue by kernalkue** [League-of-Foundry-Developers/fvtt-module-popout#34]
My players haven't noticed (because typically they only have the one token) but it's a nightmare for me as a DM.

Pressing ESC when I have a popped out window has no effect. Doesn't deselect my selected token. Doesn't open the ESC menu.

Foundry 0.7.5
PopOut! 1.0
System: DnD5e
(Have tested with no other modules loaded)

**Comment by kakaroto** [comment]
😱 did I break it!!! 
Sorry! Will check and fix it asap, thanks!

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue soon. It would help if you describe the expected behavior. If you have the popped out window focused, what do you expect the escape button to do?

**Comment by kernalkue** [comment]
With the popped out window focused, I would expect ESC to have no effect.
In the main app, I would expect it to behave as it normally would without a pop-out. I appreciate this may be tricky though (after exploring it more myself), because the standard behaviour is for the ESC key to close open floating panels and I assume that's why its closing the popped-out window.

**Comment by Posnet** [comment]
This should be fixed in the next release.
