### ISSUE TITLE
[SUGGESTION] Do not show the "popout" action from the Foundry client

### ISSUE THREAD

**Issue by JJBocanegra** [League-of-Foundry-Developers/fvtt-module-popout#36]
Because the popout does not work on the Foundry standalone client, remove all references to it in all windows, so as not to clutter the window headers.

**Comment by kakaroto** [comment]
That would mean I would be answering every day, support questions or bug reports of "I enabled the module and it didn't add the popout button" for those who don't know it can't work in the electron browser. This might clutter it, but it's still needed.

**Comment by JJBocanegra** [comment]
And what about an option to hide it, disabled by default?

**Comment by kakaroto** [comment]
That would work, yeah. Those disabling it would already know that it doesn't work there.

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue soon and will follow the suggestion on completely hiding the module for native clients.
