### ISSUE TITLE
Lateral tabs

### ISSUE THREAD

**Issue by parvusdomus** [League-of-Foundry-Developers/fvtt-module-popout#37]
When you use popout in a character (or item) sheet that includes lateral tabs like the one in the image (swade system, swade pulp module) the new window includes the main part of the sheet but leaves the tabs out, you can access them using the scroll bar in the bottom, but it'll be better having the complete sheet.
![Captura de pantalla -2021-02-11 09-46-19](https://user-images.githubusercontent.com/71666845/107616352-2b9eac00-6c4e-11eb-8e40-7500e7841f76.png)

**Comment by Posnet** [comment]
Hi, I have taken over maintenance of this module. I will look into this issue as soon. I am not familiar with this particular module. Could you please let me know the manifest url and the version you are using?

**Comment by parvusdomus** [comment]
Hello Posnet,

First of all thanks for taking care of maintaining this module.

I'm using Foundry 0.7.9 with swade system version 1.16.2 with the community sheet, popout ver 1.0 and swade pulp edition ver 1.5 (this is the one that adds the side tabs to the swade community sheet).

"manifest": "https://gitlab.com/peginc/swade/-/raw/master/src/system.json"
"manifest": "https://raw.githubusercontent.com/League-of-Foundry-Developers/fvtt-module-popout/master/module.json"
"manifest": "https://gitlab.com/mesfoliesludiques/foundryvtt-swade-pulpedition/-/raw/master/module.json"

If you need any other info or have any question, please let me know.
Thanks again and Regards
