### ISSUE TITLE
[Suggestion] Would it be possible to have PopOut! work "externally" ?

### ISSUE THREAD

**Issue by mummson** [League-of-Foundry-Developers/fvtt-module-popout#39]
Not sure if it's ok to make suggestions as "issues" I wasn't sure if DM-ing on discord would be preferred or no.

I'd like to be able to "popout" windows to another device, I'm mostly thinking about character sheets. So that you could have your character sheet open on a tablet/phone or laptop, also this would be extremely useful when playing "on-site" since it would eliminate the need to write/print out all characters/npc's for each play. Either the DM would give players the unique URL for each sheet or they could generate it themselves.

There is a separate [module](https://github.com/ardittristan/VTTExternalActorViewer) that does this, but it needs to be coded to work with each specific game system. I was hoping this could be an "easy" feature to add on to PopOut!

**Comment by Posnet** [comment]
Hi @mummson, I have token over maintenance of this module so will address your question now. 

Unfortunately there is no way to solve this problem for arbitrary game systems without deep integration with foundry core. With the current way Popout works it will only every be able to work on a single device, and in particular a single browser on that device. 

I have actually tried to make this work, similarly to the module you mentioned, and while it can display character sheets, it actually ends up behaving as if multiple connections have been opened for a single player. Which foundry does not like and can cause unexpected behaviour.

It may be possible to safely have a read only url for specific applications, however likely not for arbitrary game systems as you have encountered.

**Comment by mummson** [comment]
That's a damn shame, I really want to be able to somehow use the character sheets when playing locally with out everyone having to have laptops and such on the table :)

**Comment by Posnet** [comment]
An alternative I have started using for my own games is to create a new player that only has read only permissions to things. I've been using it for DMing so that I can use an ipad, but you could make a second read only one for player's tokens also. It might be a hassle to set up but it would work with everything.
