### ISSUE TITLE
Foundry Update Error:  Cannot read property 'version'

### ISSUE THREAD

**Issue by PointFrankRange** [League-of-Foundry-Developers/fvtt-module-popout#50]
Foundry Version:  0.8.7
PopOut! Version: 1.2

When attempting to check for an update in Foundry for the PopOut! module I am encountering an error message that the 'Version' property of the Module application is not defined.

![image](https://user-images.githubusercontent.com/68871430/123123467-da30d580-d414-11eb-9bf6-27a13f8b6850.png)

**Comment by Drakynn** [comment]
Also receiving this error.

**Comment by envy** [comment]
The download url in the manifest is wrong as the manifest already says version 2.1 is available but there is no tagged release with that version yet.

You can install 2.0 manually using this manifest URL: https://raw.githubusercontent.com/League-of-Foundry-Developers/fvtt-module-popout/v2.0/module.json

Updating will still be broken but at least you'll be on v2.0.

**Comment by Posnet** [comment]
Apologies, I pushed to the wrong branch. Should be fixed now.
