### ISSUE TITLE
Compatability with Next Up

### ISSUE THREAD

**Issue by kandashi** [League-of-Foundry-Developers/fvtt-module-popout#54]
Theres a bit of an odd issue when using Next Up to popout a character sheet. Once you cycle through the combatants once the next time a tokens sheet is "popped out" it leaves a blank sheet behind like this 
![image](https://user-images.githubusercontent.com/1347785/128574613-bae81b2d-b183-447e-8ea6-647a71fa8d46.png)

If you try to close this sheet it then pops in the actor sheet, but fullscreen and unclosable (see https://github.com/kandashi/Next-Up/issues/81)

**Comment by Posnet** [comment]
Can you please confirm the version of PopOut you are using? v2.0 added code to make popout idempotent, and it stabilized a public api.

**Comment by kandashi** [comment]
Very sorry for this, my "update all" button has been playing silly buggers apparently. I was on 1.3, on 2.1 it works as intended ❤️
