### ISSUE TITLE
No issues found for Foundry 9.0

### ISSUE THREAD

**Issue by CarolinaGuy89** [League-of-Foundry-Developers/fvtt-module-popout#60]
No issues were found in testing this Module in Foundry Version 9 - Build 238

Locally, I changed module.json, row 44 from "compatibleCoreVersion": "0.8.9" to "compatibleCoreVersion": "0.9.9".
No problems were identified in my testing (Chrome), using Starfinder game system.

Apologies for not really knowing github enough to make the Pull Request without fear of breaking something.

**Comment by CaosFR** [comment]
Same for me, no issue, please make a update.

**Comment by CaosFR** [comment]
Thanks for the update.
