### ISSUE TITLE
Add option to create tab instead of popup

### ISSUE THREAD

**Issue by crepererum** [League-of-Foundry-Developers/fvtt-module-popout#67]
# Abstract
Popouts are somewhat floating around and cannot be grouped, because they don't offer the tab functionality of normal browser tabs. Esp. when keeping characters sheets around, it would be nice to have multiple popouts grouped in a fully-featured browser window (e.g. on a secondary monitor) or to just be able to get the popout out of the way and use browser tabs to switch between the main screen and a popout. For this it would be nice if popouts could be created as normal browser tabs instead of windows w/o any decoration. This should likely be an option or additional button, because many people might prefer the current style.

# Technical Details
The [`window.open()` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) that is used to create the popout window here

https://github.com/League-of-Foundry-Developers/fvtt-module-popout/blob/dcc327ac0fe5fd78d6c45731224646cd067477a0/popout.js#L378

allows you to specify the [`popup` feature](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#popup_feature). Because there are some window features passed, this defaults to `popup=1`, but could be set to `popup=0` to open a new tab.

# PS
Thank you for this great module! :slightly_smiling_face:

**Comment by Posnet** [comment]
There is an option in the settings called Pop sheet out into windows. I think this does what you want already (if you disable the option the popout will be a new tab instead of a window.)

**Comment by crepererum** [comment]
Thanks. I'll try that out and report back the results when I'm back at my PC (next week).

**Comment by crepererum** [comment]
Verified, thanks!
