### ISSUE TITLE
[BUG] Cannot add gold to character sheet when window is popped out

### ISSUE THREAD

**Issue by sspokowski** [League-of-Foundry-Developers/fvtt-module-popout#68]
# Description
When a character sheet has been popped out, the "Add Coins" button in the "Add Coins" modal dialog has no effect.

## Game Details

- Foundry VTT Version: 9
- Foundry VTT Build: 249
- Game: Pathfinder 2nd Edition (3.3.1.10311)
- PopOut! version: 2.5

## Steps to reproduce

 - Open PC character sheet
 - PopOut! character
 - Navigate to ***Inventory*** tab
 - Click + (plus sign) in the ***Coins*** banner
 - On the ***Add Coins*** dialog, fill in one or more of the input boxes with a number
 - Click the ***Add Coins*** button
 

## Expected Behavior
Coins should be added to character sheet (behavior should match the popped in version)

**Comment by Posnet** [comment]
I have been unable to reproduce the issue. Please attach a copy of the world you are using. Or an example world that demonstrates the issue.
Please also let me know what operating system and browser you are using.

**Comment by sspokowski** [comment]
Seems to be a Firefox issue only. I just tested in Chrome and it is working as expected. I'm on Windows 10 with the latest stable builds of both browsers, and the game is hosted on The Forge. 

I think this issue could be closed.  I can host the game locally and try debugging this weekend though if you'd like some more information.

**Comment by Posnet** [comment]
Interesting, I tested on firefox on linux and it also doesn't have the issue. I will up a windows VM this weekend to test myself.

**Comment by Posnet** [comment]
I have been unable to reproduce this issue. If it is still a problem please message me with a zipped copy of the world you are experiencing the issue on. `popout <at> denialof.services`
