### ISSUE TITLE
Issues with Dialog

### ISSUE THREAD

**Issue by dabeech** [League-of-Foundry-Developers/fvtt-module-popout#71]
I’m currently having issues with pulling a value from a dialog when the character sheet is popped out.

My current weapon attack rolls happen in this order: click > dialog to grab situational mods and choose normal, disadvantage, or advantage > send to chat > damage from button in chat.

I have tried using `find` on my selector, but everything I try turns up either null or undefined. My other rolls from the sheet are working fine, so I’m guessing that the dialog is the culprit.

Any help is appreciated!

Current code (pre-PopOut! fix):
```js
// the dialog
const rangedDialog = new Dialog({
            title: "Ranged Attack Modifiers",
            content: weaponDialogContent,
            buttons: {
              button1: {
                label: "Disadvantage",
                callback: (html) => rangedDisad(html)
              },
              button2: {
                label: "Normal Attack",
                callback: (html) => rangedNorm(html)
              },
              button3: {
                label: "Advantage",
                callback: (html) => rangedAdv(html)
              }
            },
            default: "button2"
          }).render(true);
```
```js
// the Normal Attack (default) button, aka "button2"
async function rangedNorm(html) {
     let sitMod = parseInt(document.getElementById("sitMod").value, 10);
     let norm = await new Roll("1d20 + @rollData.abilities.dex.mod + @rollData.attributes.attackBonus.value + @sitMod", {rollData, sitMod}).evaluate({async: true});
     // the rest of the function below here, but that's not important to the issue```

**Comment by Posnet** [comment]
Please read the section in the README about module compatibility.
But the gist is when ever you are searching for a HTML element, you must do it from a HTML object attached to a Foundry application, never the global window or document objects.
