### ISSUE TITLE
a popped out Combat window will sometimes get stuck and not allow the DM to close it.

### ISSUE THREAD

**Issue by rtschaefer** [League-of-Foundry-Developers/fvtt-module-popout#74]
On a couple of occasions now, I have noticed that when I popout the combat window (so I can move it to a secondary monitor), after the combat is over, the combat window will not allow me to close it. The remedy I found, is to highlight a couple tokens and start a brand new combat and then simply end it right away. That seems to reset things and I can then close the stuck window. I am not sure if this is a conflict with another module, or if it is something strange about my own setup.  

Popout is an absolute must have module, and if this is the worst bug I have, then all is good indeed! Thank you.,

**Comment by Posnet** [comment]
Could you please provide the operating system, browser, foundry version you are using?
