### ISSUE TITLE
Typing in PopOut windows and Configure Controls shortcuts

### ISSUE THREAD

**Issue by lipefl** [League-of-Foundry-Developers/fvtt-module-popout#76]
When using a popout window and you use one of the "Configure Controls" shortcuts, it acts like I was in the main window using the shortcut. 
For example: if i try to put number 2,4,6 or 8 using numpad in the name field of a PopOut sheet, it'll move the screen, instead of typing. It doesn't happen if i use the sheet without PopOut.

Tested using Savage Worlds SWADE system

Maybe a useful information: it wasn't happening when i was using PopOut 1.0, it started when i upgrade PopOut to the last version.

**Comment by Dialectikal** [comment]
Also tested with the DnD5e system

**Comment by Posnet** [comment]
Thanks, I am aware of this issue an am working on a fix. This was caused by https://github.com/League-of-Foundry-Developers/fvtt-module-popout/commit/e9e127381340975a224c5220dfa7e276858bd911

**Comment by supernun** [comment]
Which version has this fix? On forge I have 2.7 and it still exhibits this issue.

**Comment by Posnet** [comment]
What browser and OS are you using?

**Comment by Posnet** [comment]
Nevermind, I worked out what the issue was. should be fixed in 2.8.

**Comment by supernun** [comment]
Looks fixed to me! Thanks!
