### ISSUE TITLE
Force to open in a new window doesn't work

### ISSUE THREAD

**Issue by nikolasbasler** [League-of-Foundry-Developers/fvtt-module-popout#79]
Hello,

this is my setup:
MacOS 12.4
Chrome 103.0.5060.114
Foundry 9, build 269 (running on Molten Hosting)
lib-wrapper 1.12.7.0
PopOut! 2.8

When I run Chrome on fullscreen and click the icon to pop out a window, it will appear in a new tab instead of a new window, despite the option to force a new window is activated. In windowed mode (i.e. not in fullscreen), the behaviour is as expected.

It's not a major problem, but a bit inconvenient.

Cheers and thanks for making this cool module! It's neat and very helpful.

**Comment by Posnet** [comment]
Unfortunately this is the built in behavior of chrome on macos in fullscreen, pages are unable to open new windows if the current window is full screen.
