### ISSUE TITLE
v10 Problems

### ISSUE THREAD

**Issue by Posnet** [League-of-Foundry-Developers/fvtt-module-popout#81]
- `game.Keyboard.isDown` no longer exists
- game has switched to proseMirror, so editor has broken

**Comment by oestred** [comment]
following issue

**Comment by Posnet** [comment]
the basic compatibility issues have been fixed on the v10 branch. I'll likely merge and cut a release today or tomorrow.

But the editor is going to require major changes in the base foundry code.
All of the custom editor code is littered with document.getElementById and similar dom specific code that will make it impossible to support the new editor in popouts in it's current form.
