### ISSUE TITLE
Warning messages with v2.9 under v10.286

### ISSUE THREAD

**Issue by steveculshaw** [League-of-Foundry-Developers/fvtt-module-popout#86]
I'm seeing warning about module "popout" using ...

1. "name", which is deprecated in favour of "id"
2. "dependencies", which is deprecated in favour of "relationships.requires"

![image](https://user-images.githubusercontent.com/64320/192142050-019ce206-2f35-4ed2-8490-60277cc15b6e.png)

**Comment by Posnet** [comment]
Those keys are required in order to maintain compatibility with version 9 of foundry.
I try ensure it supports both the current and previous major release.
I will remove them them when version 11 is released and I increase the minimum version to version 10.

**Comment by steveculshaw** [comment]
Ah ha ... sounds sensible

Thanks for the response, and for creating the module
