### ISSUE TITLE
Enhancement: Move _disable_popout_module to `app.options`

### ISSUE THREAD

**Issue by typhonrt** [League-of-Foundry-Developers/fvtt-module-popout#90]
A cleaner solution is to move `app._disable_popout_module` to `app.options` perhaps making it `app.options.disable_popout_module`. This allows it to be configured in many ways through Application and Dialog constructors without having to modify / place an attribute on a created Application. 

This also allows it to be added to Dialog static methods `prompt` and `confirm`, etc.  
Ex:
```js
Dialog.prompt({ title: '', options: { disable_popout_module: true }});
```

You can keep the old location if necessary for compatibility, but also add the `app.options.disable_popout_module` possibility as well.

I'd be glad to submit a PR for this that could be grouped into the other PRs for the next module release.

**Comment by Posnet** [comment]
This feature is actually already available via the `popOutModuleDisable` attribute, but I guess I forgot to document it. I will add it to the disable section of the Readme.

**Comment by typhonrt** [comment]
Yeah I saw that eventually... :D Welcome back... Hope the holiday was awesome!
