### ISSUE TITLE
Font not working in popped out window

### ISSUE THREAD

**Issue by Kerdude** [League-of-Foundry-Developers/fvtt-module-popout#91]
The PF2e system uses a font to display action icons. It's located at /home/user/foundryuserdata/Data/systems/pf2e/fonts/Pathfinder2eActions.ttf

When some sheets (character, NPC, items, etc) are popped out, that font reverts to its alphanumeric representation (letters A, D, T, etc)

![image](https://user-images.githubusercontent.com/77137657/200184952-9ca579de-dc3d-40be-adf1-1f7a4b9e57ba.png)

![image](https://user-images.githubusercontent.com/77137657/200184960-16de6269-cff4-4c8e-8a30-5225bdbe52ec.png)

**Comment by typhonrt** [comment]
I can help with this as this basically involves loading the new v10 FontConfig / fonts into the new browser document. Already have the code for this for loading FontConfig fonts into TinyMCE / IFrame which is the same thing.

**Comment by Posnet** [comment]
I already have a fix for this, I am putting together  a new release at the moment
