### ISSUE TITLE
PF2e Equipped Items Swapping

### ISSUE THREAD

**Issue by Tsurumah** [League-of-Foundry-Developers/fvtt-module-popout#95]
I know the module was originally intended solely for D&D 5e, but I've been using it for PF2e and its been working great! Except for one thing that's odd: you can't seem to change how your items are equipped while the sheet is popped out; not a huge issue, of course, because popping it back in, changing it, and popping it back out works just fine.

**Comment by Posnet** [comment]
Sorry for the long reply. However this is not fixable on my end due to how the popout functionality is implemented, it could only be fixed by the pathfinder module, and after having a cursory look, it would be a lot of work for them due to their extensive use of JQuery event listeners.
