### ISSUE TITLE
When using PopOut the Foundry provided `data-tooltip` CSS attribute does not work

### ISSUE THREAD

**Issue by ryanwalder** [League-of-Foundry-Developers/fvtt-module-popout#97]
Hi I'm a developer on the [Cyberpunk RED Core](https://foundryvtt.com/packages/cyberpunk-red-core) system and we make heavy use of the `data-tooltip` CSS attribute for tooltips to provide information to the player for sheet functionality. Unfortunately when using PopOut this does not work.

Example, Character Sheet not Popped Out (but module active):

![Peek 2023-02-23 18-52](https://user-images.githubusercontent.com/10901150/221002969-e5e8746e-6103-40cf-849b-8607a953fb9a.gif)

Example, Character Sheet Popped Out:

![Peek 2023-02-23 18-49](https://user-images.githubusercontent.com/10901150/221002729-74cdd9ff-c5da-45f9-994a-fc9f4f56dad2.gif)

Is this a PopOut bug or is there potentially anything we could do to support PopOut better?

**Comment by Posnet** [comment]
PopOut should preserve all css imports in popouts. Could you please provide the OS, Browser, foundry version and module/system versions for me to reproduce the issue. Ideally if you can provide a zip file of a test world, that would be appreciated.

**Comment by ryanwalder** [comment]
Versions:

VTT: v10.291 (NodeJS v19.7.0)  
[CPRC](https://foundryvtt.com/packages/cyberpunk-red-core): v0.86.1  
OS: Arch Linux (up to date)  
Browser: Firefox  v110.0

Also to note: This bug was raised to me from a Windows 10 user, not 100% sure which browser they were using.

This happens on all worlds using Cyberpunk RED but here is a test setup world: [popout-example.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/files/10826020/popout-example.zip)

Here are some more relevant gifs showing the issue (the ones above were taking in my dev branch where I'm rewriting the sheet and remembered about this bug):

PopOut Module loaded, sheet not popped out:

![popout-in](https://user-images.githubusercontent.com/10901150/221225422-bd82cacb-908e-4059-954b-b266423ec157.gif)

PopOut Module loaded, sheet popped out:

![popout-out](https://user-images.githubusercontent.com/10901150/221225514-b16be7c4-1495-41e6-ac5c-f6da96884350.gif)

**Comment by Posnet** [comment]
Thank you for the additional information that is very helpful.
I have identified the cause as being Tooltip manager of global document access. This will require a complex set of global monkey patches similar to ba31dc2 to fix. 
And you are correct this is broken for all tooltips as of v10.

**Comment by Posnet** [comment]
@ryanwalder I have pushed a partial fix with the latest release 2.13, it ended up being more complex to try and fix than I expected, and it will only fix the basic data-tooltip use case. Direct `tooltip.activate` calls in a system are still broken, and are un-fixable.
