### ISSUE TITLE
PF2e - expand description while popped out

### ISSUE THREAD

**Issue by Thebazilly** [League-of-Foundry-Developers/fvtt-module-popout#98]
I know the module is only tested with DnD 5e, but it's worked so well in the past that it's debilitating to play without now. Hopefully it can be core Foundry functionality someday.

I am on Foundry v10 291, PF2e system version 4.8.1. When I pop out a window for an Actor, the ability and spell headings can no longer be clicked on to expand the descriptions. The headings will remain expanded if I click them in the Foundry window first, then pop out the window.

**Comment by LEGOL2** [comment]
I confirm that I also have this issue. This worked fine in earlier version.

**Comment by propri** [comment]
In foundry v10 291, PF2e 4.9.3  
Using Firefox (110) the spell headings **cannot** be expanded when a character sheet is popped out.  
Using Chrome (110) the spell headings **can** be expanded when a character sheet is popped out.

**Comment by propri** [comment]
A warning can be seen on the console in Firefox when clicking a spell heading:

```
Opening multiple popups was blocked due to lack of user activation. popout.js:816:13
```

**Comment by The-RavenKing** [comment]
I'm having an issue in foundry v10.291 with pathfinder 2e where when looking at my spells instead of showing actions required for the spell it just shows a letter.

**Comment by BeachNinja** [comment]
In Firefox 112.0.2 and Foundry build 10.291 with Pf2e 4.9.3 and PopOut! 2.12 no headers can be expanded when windows are popped out and I get the message 
"Opening multiple popups was blocked due to lack of user activation." in the console.

**Comment by Posnet** [comment]
This is a problem with Firefox and JQuery, after extensive testing there is nothing I can fix on  my side. And will have to drop support for Firefox. Please see the README for more details.
