### ISSUE TITLE
"field.dataset is undefined" when casting a spell from a popped out window in firefox

### ISSUE THREAD

**Issue by txm3278** [League-of-Foundry-Developers/fvtt-module-popout#99]
![image](https://user-images.githubusercontent.com/25332081/229591064-65ce8cc5-2951-4ec5-99ae-f1fd4ed50162.png)

Using D&D Beyond Importer with full automation and Chris's Premades.

This example is trying to cast flame strike at 5th level. This works fine when the character sheet is not popped out. Also works when the character sheet is popped out in Chrome but not in Firefox.

**Comment by Posnet** [comment]
JQuery and popouts are basically broken and will never work. But they are particularly broken on Firefox, and so I am dropping support for that browser unfortunately, please see the README for more details.
